version: '2'
services:
    winterpokal-app:
        image: winterpokal
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://winterpokal-postgresql:5432/winterpokal
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8078:8078
    winterpokal-postgresql:
        extends:
            file: postgresql.yml
            service: winterpokal-postgresql
